GET http://localhost:8000/api/users/all HTTP/1.1
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZTMzMGY3Zjc0YjAxMjJlZTY3Nzg1MiIsImlhdCI6MTY0MjI4MDk4OCwiZXhwIjoxNjQyMjgyNzg4fQ.bCtndtkz1mZ9ARibyM9bSofhezw9_4vHmk7yambLmcU
###
POST http://localhost:8000/api/users/signup HTTP/1.1
Content-Type: application/json

{
  "name": "freddy",
  "email": "freddy@gmail.com",
  "password": "freddy",
  "image": ""
}
###
POST http://localhost:8000/api/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "freddy@gmail.com",
  "password": "freddy"
}
###
GET http://localhost:8000/api/users/about HTTP/1.1
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZTMzMGY3Zjc0YjAxMjJlZTY3Nzg1MiIsImlhdCI6MTY0MjI4NzcwOSwiZXhwIjoxNjQyMjg5NTA5fQ.ZjUgS5gzjP7Lk4QXGZEkFBXxh1cifLGrEYAJytPQm2w